version: "3.9"

services:
  # ───────────────────────────────────── Redis (broker / backend)
  redis:
    image: redis:7-alpine

  # ───────────────────────────────────── Celery worker
  worker:
    build: ./worker                   # contains tasks.py + requirements.txt
    command: celery -A tasks worker --loglevel=info
    env_file: .env                    # << inject EVERYTHING from .env
    depends_on: [redis]

  # ───────────────────────────────────── Producer helper
  #
  # Starts idle so you can exec into it (or run one-shot commands).
  # Uses the same Python base to keep deps consistent.
  #
  producer:
    build: ./producer
    entrypoint: ["sleep", "infinity"]
    env_file: .env                    # only needed if you want vars inside
    depends_on: [redis]
